"""Wait until GitHub Pages serves the data generated by the current run."""
from __future__ import annotations

import argparse
import json
import time
from pathlib import Path
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit
from urllib.request import Request, urlopen


def _cache_busted(url: str, attempt: int) -> str:
    parts = urlsplit(url)
    query = dict(parse_qsl(parts.query))
    query["verify"] = str(attempt)
    return urlunsplit(
        (parts.scheme, parts.netloc, parts.path, urlencode(query), parts.fragment)
    )


def live_matches(expected: dict, live: dict) -> tuple[bool, str]:
    if not isinstance(expected, dict) or not isinstance(live, dict):
        raise ValueError("expected and live payload roots must be objects")
    expected_time = expected.get("generated_at")
    live_time = live.get("generated_at")
    if live_time != expected_time:
        return False, f"generated_at is {live_time!r}, expected {expected_time!r}"
    expected_count = len(expected.get("instruments") or [])
    live_count = len(live.get("instruments") or [])
    if live_count != expected_count:
        return False, f"instrument count is {live_count}, expected {expected_count}"
    if live != expected:
        return False, "live payload content differs from the published export"
    return True, f"live payload matches {expected_time} with {live_count} instruments"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--expected", type=Path, required=True)
    parser.add_argument("--url", required=True)
    parser.add_argument("--attempts", type=int, default=24)
    parser.add_argument("--interval-seconds", type=float, default=15)
    args = parser.parse_args()
    expected = json.loads(args.expected.read_text(encoding="utf-8"))
    last_reason = "no request attempted"
    for attempt in range(1, args.attempts + 1):
        try:
            request = Request(
                _cache_busted(args.url, attempt),
                headers={"Cache-Control": "no-cache"},
            )
            with urlopen(request, timeout=30) as response:
                live = json.load(response)
            matched, last_reason = live_matches(expected, live)
            if matched:
                print(last_reason)
                return
        except (OSError, ValueError, json.JSONDecodeError) as exc:
            last_reason = str(exc)
        if attempt < args.attempts:
            time.sleep(args.interval_seconds)
    raise SystemExit(f"live verification failed: {last_reason}")


if __name__ == "__main__":
    main()
